### ISSUE TITLE
Typo on the homepage

### ISSUE THREAD

**Issue by ionut-botizan** [dblens/app#29]
I don't know if this is the right place to report this, but there's a typo on your homepage and, I don't know why, it was the first thing I noticed... :)
You are missing a "r" in the sub-title, in the "PostgreSQL" name.

![image](https://user-images.githubusercontent.com/408501/137450057-23c24f0a-8566-4b09-b107-222b4bf4f4a8.png)

**Comment by soorajshankar** [comment]
ahh my bad! will fix this soon! 

Thanks for reporting!

Dupe : https://github.com/dblens/app/issues/27
